# Generated by Django 2.2 on 2020-01-11 08:36

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0002_auto_20200111_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zoo.Gender'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='gender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zoo.Gender'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 12, 8, 36, 4, 687146, tzinfo=utc)),
        ),
    ]
