# Generated by Django 2.2 on 2020-01-10 07:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0002_animalgender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('name', models.CharField(default='organism', max_length=256)),
                ('incoming_time', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('animal_type', models.ForeignKey(default='this', on_delete=django.db.models.deletion.SET_DEFAULT, to='zoo.AnimalType')),
                ('gender', models.ForeignKey(default='it', on_delete=django.db.models.deletion.SET_DEFAULT, to='zoo.AnimalGender')),
            ],
        ),
    ]
