# Generated by Django 2.2 on 2020-01-10 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0003_animal'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='all_age', max_length=20)),
                ('age_from', models.PositiveSmallIntegerField(default=0)),
                ('age_to', models.PositiveSmallIntegerField(default=122)),
            ],
        ),
    ]
