# Generated by Django 2.2 on 2020-01-10 09:58

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0004_agerange'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valid_until', models.DateTimeField(default=datetime.datetime(2020, 1, 11, 9, 58, 51, 520206, tzinfo=utc))),
                ('age_range', models.ForeignKey(default='all_age', on_delete=django.db.models.deletion.SET_DEFAULT, to='zoo.AgeRange')),
            ],
        ),
    ]
