# Generated by Django 2.2 on 2020-01-10 11:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('zoo', '0005_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 11, 11, 51, 11, 45428, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
