# Generated by Django 2.2 on 2020-01-10 12:00

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0006_auto_20200110_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='visitor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='zoo.Visitor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticket',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 11, 11, 59, 32, 397577, tzinfo=utc)),
        ),
    ]
