# Generated by Django 2.2 on 2020-01-10 12:12

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('zoo', '0007_auto_20200110_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='valid_until',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 11, 12, 12, 36, 996613, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='VisitingAnimals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_time', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='zoo.Animal')),
                ('visitor', models.ForeignKey(default='some_user', on_delete=django.db.models.deletion.SET_DEFAULT, to='zoo.Visitor')),
            ],
        ),
    ]
